Corrected custom actions

diff --git a/.github/workflows/build/action.yaml b/.github/workflows/build/action.yaml
--- a/.github/workflows/build/action.yaml
+++ b/.github/workflows/build/action.yaml
@@ -1,54 +1,47 @@
 name: 'build-genomic-tools'
+description: Build Genomic Tools
 
-on:
-  workflow_call:
-    inputs:
-      stage:
-        type: string
-        description: 'Whether to build, test or deploy'
-      tools-dir:
-        type: string
-        description: 'The  name of the directory that contains tools.'
-        required: true
-        default: 'tools'
-      tools-modified:
-        type: string
-        description: 'The tools that have been modified'
-        required: false
-      build-version:
-        type: string
-        description: 'The build versio of the docker image'
-        required: true
+inputs:
+  stage:
+    description: 'Whether to build, test or deploy'
+  tools-dir:
+    description: 'The  name of the directory that contains tools.'
+    required: true
+    default: 'tools'
+  tools-modified:
+    description: 'The tools that have been modified'
+    required: false
+  build-version:
+    description: 'The build version of the docker image'
+    required: true
 
-jobs:
-  build:
-    name: get-modified
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: build
-        run: |
-          for TOOL in ${TOOLS_MODIFIED}; do
-            if [ "$TOOL" == "README.md" ]; then
-              echo "README.md modified moving on"
+runs:
+  using: composite
+  steps:
+    - name: Checkout
+      uses: actions/checkout@v2
+    - name: build
+      run: |
+        for TOOL in ${TOOLS_MODIFIED}; do
+          if [ "$TOOL" == "README.md" ]; then
+            echo "README.md modified moving on"
+          else
+            bash -x "${GITHUB_ACTION_PATH}/scripts/stage-${STAGE}.sh" "${TOOL}"
+            if [ $? -eq 0 ]; then
+              echo "Stage ${CI_JOB_STAGE} for ${TOOL} succeeded."
             else
-              bash -x "${GITHUB_ACTION_PATH}/scripts/stage-${STAGE}.sh" "${TOOL}"
-              if [ $? -eq 0 ]; then
-                echo "Stage ${CI_JOB_STAGE} for ${TOOL} succeeded."
-              else
-                echo "Stage ${CI_JOB_STAGE} for ${TOOL} failed. Exiting."
-                exit 1
-              fi
-           fi
-          done;
-        shell: bash
-        env:
-          STAGE: ${{ inputs.stage }}
-          REF: ${{ github.ref_name }}
-          TOOLS_MODIFIED: ${{ inputs.tools-modified }}
-          BUILD_VERSION: ${{ inputs.build-version }}
-          GITHUB_ACTION_PATH: ${{ github.action_path }}
-          DOCKER_IO_USER: ${{ secrets.DOCKER_IO_USER }}
-          DOCKER_IO_PASSWORD: ${{ secrets.DOCKER_IO_PASSWORD }}
-          EXTERNAL_REGISTRY: ${{ secrets.EXTERNAL_REGISTRY }}
+              echo "Stage ${CI_JOB_STAGE} for ${TOOL} failed. Exiting."
+              exit 1
+            fi
+         fi
+        done;
+      shell: bash
+      env:
+        STAGE: ${{ inputs.stage }}
+        REF: ${{ github.ref_name }}
+        TOOLS_MODIFIED: ${{ inputs.tools-modified }}
+        BUILD_VERSION: ${{ inputs.build-version }}
+        GITHUB_ACTION_PATH: ${{ github.action_path }}
+        DOCKER_IO_USER: ${{ secrets.DOCKER_IO_USER }}
+        DOCKER_IO_PASSWORD: ${{ secrets.DOCKER_IO_PASSWORD }}
+        EXTERNAL_REGISTRY: ${{ secrets.EXTERNAL_REGISTRY }}
