Fixed github vars to gitea

diff --git a/.gitea/workflows/build/action.yaml b/.gitea/workflows/build/action.yaml
--- a/.gitea/workflows/build/action.yaml
+++ b/.gitea/workflows/build/action.yaml
@@ -1,48 +1,56 @@
 name: 'build-genomic-tools'
-description: 'Build Genomic tools'
-on:
-  workflow-call:
-    inputs:
-      stage:
-        description: 'Whether to build, test or deploy'
-      tools-dir:
-        description: 'The  name of the directory that contains tools.'
-        required: true
-        default: 'tools'
-      tools-modified:
-        description: 'The tools that have been modified'
-        required: false
-      build-version:
-        description: 'The build versio of the docker image'
-        required: true
+description: Build Genomic Tools
 
-jobs:
-  build:
-    name: get-modified
-    runs-on: default
-    steps:
-      - name: build
-        run: |
-          for TOOL in ${TOOLS_MODIFIED}; do
-            if [ "$TOOL" == "README.md" ]; then
-              echo "README.md modified moving on"
+inputs:
+  stage:
+    description: 'Whether to build, test or deploy'
+  tools-dir:
+    description: 'The  name of the directory that contains tools.'
+    required: true
+    default: 'tools'
+  tools-modified:
+    description: 'The tools that have been modified'
+    required: false
+  build-version:
+    description: 'The build version of the docker image'
+    required: true
+  docker-user:
+    description: 'The build version of the docker image'
+    required: false
+  docker-passwd:
+    description: 'The build version of the docker image'
+    required: false
+  registry:
+    description: 'registry'
+    required: false
+
+runs:
+  using: composite
+  steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+    - name: build
+      run: |
+        for TOOL in ${TOOLS_MODIFIED}; do
+          if [ "$TOOL" == "README.md" ]; then
+            echo "README.md modified moving on"
+          else
+            bash -x "${GITEA_ACTION_PATH}/scripts/stage-${STAGE}.sh" "${TOOL}"
+            if [ $? -eq 0 ]; then
+              echo "Stage ${CI_JOB_STAGE} for ${TOOL} succeeded."
             else
-              bash -x "${GITEA_ACTION_PATH}/scripts/stage-${STAGE}.sh" "${TOOL}"
-              if [ $? -eq 0 ]; then
-                echo "Stage ${CI_JOB_STAGE} for ${TOOL} succeeded."
-              else
-                echo "Stage ${CI_JOB_STAGE} for ${TOOL} failed. Exiting."
-                exit 1
-              fi
-           fi
-          done;
-        shell: bash
-        env:
-          STAGE: ${{ inputs.stage }}
-          REF: ${{ github.ref_name }}
-          TOOLS_MODIFIED: ${{ inputs.tools-modified }}
-          BUILD_VERSION: ${{ inputs.build-version }}
-          GITEA_ACTION_PATH: ${{ gitea.action_path }}
-          DOCKER_IO_USER: ${{ secrets.DOCKER_IO_USER }}
-          DOCKER_IO_PASSWORD: ${{ secrets.DOCKER_IO_PASSWORD }}
-          EXTERNAL_REGISTRY: ${{ secrets.EXTERNAL_REGISTRY }}
+              echo "Stage ${CI_JOB_STAGE} for ${TOOL} failed. Exiting."
+              exit 1
+            fi
+         fi
+        done;
+      shell: bash
+      env:
+        STAGE: ${{ inputs.stage }}
+        REF: ${{ gitea.ref_name }}
+        TOOLS_MODIFIED: ${{ inputs.tools-modified }}
+        BUILD_VERSION: ${{ inputs.build-version }}
+        GITEA_ACTION_PATH: ${{ gitea.action_path }}
+        DOCKER_IO_USER: ${{ inputs.docker-user }}
+        DOCKER_IO_PASSWORD: ${{ inputs.docker-passwd }}
+        EXTERNAL_REGISTRY: ${{ inputs.registry }}
